//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class D_ShopOrderEntities : DbContext
    {
        public D_ShopOrderEntities()
            : base("name=D_ShopOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sh_Customer> Sh_Customer { get; set; }
        public virtual DbSet<Sh_Order> Sh_Order { get; set; }
        public virtual DbSet<Sh_OrderDet> Sh_OrderDet { get; set; }
        public virtual DbSet<Sh_Product> Sh_Product { get; set; }
        public virtual DbSet<Sh_Store> Sh_Store { get; set; }
        public virtual DbSet<Sh_User> Sh_User { get; set; }
    }
}
