//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sh_OrderDet
    {
        public int OrderDetID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> PriceAll { get; set; }
    
        public virtual Sh_Order Sh_Order { get; set; }
        public virtual Sh_Product Sh_Product { get; set; }
    }
}
