//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sh_Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sh_Product()
        {
            this.Sh_OrderDet = new HashSet<Sh_OrderDet>();
            this.Sh_Store = new HashSet<Sh_Store>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int Barcode { get; set; }
        public int Price { get; set; }
        public int Count { get; set; }
        public string Note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sh_OrderDet> Sh_OrderDet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sh_Store> Sh_Store { get; set; }
    }
}
