//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Order.Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sh_Store
    {
        public int StoreID { get; set; }
        public int Count { get; set; }
        public int ProductID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Sh_Product Sh_Product { get; set; }
    }
}
